#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "hybrid"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    windows_leader = 'alt'
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    automatic_update = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    filetree_direction = "left"
    buffer_index_type = 4
    relativenumber = false
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
#
#[layers]]
#ame = "ctrlspace"
#utosave-workspaces = true

[[layers]]
name = "shell"
default_position = "bottom"
default_height = 40

[[layers]]
 name = "colorscheme"

[[custom_plugins]]
repo = "ryanoasis/vim-devicons"

[[layers]]
name = "fzf"

[[custom_plugins]]
repo = "nvim-lua/plenary.nvim"

[[custom_plugins]]
repo = "nvim-telescope/telescope.nvim"


[[custom_plugins]]
repo = "nvim-lua/popup.nvim"


[[custom_plugins]]
repo = "nvim-telescope/telescope-media-files.nvim"

[[custom_plugins]]
name = "dracula/vim"

[[custom_plugins]]
name = "ap/vim-css-color"

[[custom_plugins]]
name = "kyazdani42/nvim-web-devicons"

[[custom_plugins]]
name = "kyazdani42/nvim-tree.lua"

[[custom_plugins]]
name = "tiagofumo/vim-nerdtree-syntax-highlight"
